### ISSUE TITLE
OpenCart 2.0 version ?

### ISSUE THREAD

**Issue by fulup-bzh** [shaman/opencart-hybridauth#1]
Tried it on Opencart 2.0 but module activation fail with 
Notice: Indirect modification of overloaded property ControllerModuleHybridAuth::$data has no effect in /home/fulup/workspace/Opencart/opencart/upload/admin/controller/module/hybrid_auth.php on line 63

I really like your method of leveraring an external hybrid authentication lib and the fact you do not impact OpenCart core.

Any intention to port this work to 2.0 ?

**Comment by Detuli83** [comment]
Thanks Shaman for providing the project. I modified it for Opencart 2.0 (Admin + Catalog), in case some wants to refer it. Never used Github (except for just using the codes available). So want to share my effort, but not sure how to share it. Please let me know if you someone needs it. I will share it on email, or guide me where can i put that

**Comment by shaman** [comment]
Thanks for your effort!
opencart.ukraine[0]gmail.com

**Comment by Detuli83** [comment]
Hi Shaman,

Please find attached the changes. I have done the following changes to
original code:

1. Modified it to suit OC 2.0 framework
2. Removed using provider icons, and used Bootstrap pure css to create
login buttons
3. Added a new field in Admin, to specify the class name to be used for
Bootstrap for each provider
4. Added Controller/View templates to be added on any page, to display
these buttons. Modules can also be created for them, but I preferred to
modify my Login page, rather than creating a module.

Know Issues:
The only problem I am not able to resolve yet is, when I pass https:*
string in scope variable s (in case of Google+ login). Please let me know
if you find any solution to that, or I will let you know I find anything.

Thanks,
Deepak Tuli

Thanks,
Deepak Tuli

**Comment by shaman** [comment]
Hi,

I did not find any attachments 

Regards

**Comment by Detuli83** [comment]
Please find my repository where I placed all files

https://github.com/Detuli83/Opencart-Hybridauth-2.0

**Comment by shaman** [comment]
Hi

Good Idea, Thanks

> 5 янв. 2015 о 20:30 Deepak Tuli <notifications@github.com> написав(ла):
> 
> https://github.com/Detuli83/Opencart-Hybridauth-2.0 <https://github.com/Detuli83/Opencart-Hybridauth-2.0>

**Comment by venusiano79** [comment]
Hi guys, 
I used  2.0 version,  I need to use it on 2.0.3.1 version. 
The installation is OK but if I place it in "account" view I don't see nothing.
can you help me please ?
